-- Spring Modulith event publication registry.
-- spring.sql.init runs this BEFORE Hibernate initializes (Spring Boot guarantee),
-- so the table is always created with TEXT columns.
-- ddl-auto=none means Hibernate will never touch this table.
CREATE TABLE IF NOT EXISTS event_publication (
    id                      UUID                     NOT NULL PRIMARY KEY,
    listener_id             TEXT                     NOT NULL,
    event_type              TEXT                     NOT NULL,
    serialized_event        TEXT                     NOT NULL,
    publication_date        TIMESTAMP WITH TIME ZONE NOT NULL,
    completion_date         TIMESTAMP WITH TIME ZONE,
    status                  VARCHAR(50)              NOT NULL DEFAULT 'PUBLISHED',
    completion_attempts     INTEGER                  NOT NULL DEFAULT 0,
    last_resubmission_date  TIMESTAMP WITH TIME ZONE
);

-- Widen columns if the table was previously created with VARCHAR(255).
ALTER TABLE event_publication ALTER COLUMN serialized_event TYPE TEXT;
ALTER TABLE event_publication ALTER COLUMN event_type        TYPE TEXT;
ALTER TABLE event_publication ALTER COLUMN listener_id       TYPE TEXT;

-- ── One-time migration: remove stale AMQP outbox rows ────────────────────────
-- After the RabbitMQ / @Externalized removal, any event_publication rows whose
-- listener_id was generated by the AMQP externalizer (contains 'amqp' or
-- 'RabbitMQ') will never be completed because that listener no longer exists.
-- This DELETE is idempotent and safe to run on every startup; it is a no-op on
-- a fresh database or after the first successful run.
DELETE FROM event_publication
WHERE  listener_id ILIKE '%amqp%'
   OR  listener_id ILIKE '%rabbitmq%';

-- ── Pipeline tracking tables (tracking module) ────────────────────────────────

-- One row per upload job. Status is recalculated as ProcessingCompletedEvents arrive.
CREATE TABLE IF NOT EXISTS pipeline_job (
    job_id            UUID        NOT NULL PRIMARY KEY,
    original_filename TEXT        NOT NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    total_files       INT         NOT NULL DEFAULT 0,
    completed_files   INT         NOT NULL DEFAULT 0,
    failed_files      INT         NOT NULL DEFAULT 0,
    skipped_files     INT         NOT NULL DEFAULT 0,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL
);

-- One row per file within a job. Updated when processing completes.
CREATE TABLE IF NOT EXISTS pipeline_file (
    file_id        UUID        NOT NULL PRIMARY KEY,
    job_id         UUID        NOT NULL,
    original_path  TEXT        NOT NULL,
    mime_type      TEXT        NOT NULL,
    status         VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
    chunks_created INT         NOT NULL DEFAULT 0,
    duration_ms    BIGINT      NOT NULL DEFAULT 0,
    error_message  TEXT,
    queued_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    processed_at   TIMESTAMP WITH TIME ZONE
);

-- ── Chat memory table (chat module) ──────────────────────────────────────────

-- Persists conversation history used by MessageWindowChatMemory / JpaChatMemoryRepository.
CREATE TABLE IF NOT EXISTS chat_message (
    id              UUID                     NOT NULL PRIMARY KEY,
    conversation_id TEXT                     NOT NULL,
    message_type    VARCHAR(20)              NOT NULL,
    content         TEXT                     NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_chat_message_conv_created
    ON chat_message (conversation_id, created_at);

